{"uuid": "bf463f60-6338-4f7e-bc65-4ba7e3d6da13", "children": ["f77de68b-63e6-4f9d-949b-58f96702f6ee"], "befores": [{"name": "create_invoice_test_data", "status": "failed", "statusDetails": {"message": "Failed: Could not load test data.\n", "trace": "  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\tests\\conftest.py\", line 98, in create_invoice_test_data\n    pytest.fail(\"Could not load test data.\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1744981068494, "stop": 1744981068495}], "start": 1744981068494, "stop": 1744981068833}