[32mINFO    [0m tests.conftest:conftest.py:74 Test data loaded successfully.
[32mINFO    [0m tests.conftest:conftest.py:105 Starting test with Chrome browser
[32mINFO    [0m WDM:logger.py:11 ====== WebDriver manager ======
[32mINFO    [0m WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
[32mINFO    [0m WDM:logger.py:11 Get LATEST chromedriver version for google-chrome
[32mINFO    [0m WDM:logger.py:11 Driver [C:\Users\Taurus13\.wdm\drivers\chromedriver\win64\135.0.7049.95\chromedriver-win32/chromedriver.exe] found in cache
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028E15C6C180>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eb0237378e059d0d2a269a4a2dfe69a8/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028E15C6C510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eb0237378e059d0d2a269a4a2dfe69a8/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028E15972F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/eb0237378e059d0d2a269a4a2dfe69a8/element
[31m[1mERROR   [0m tests.conftest:conftest.py:167 Logout failed: HTTPConnectionPool(host='localhost', port=64510): Max retries exceeded with url: /session/eb0237378e059d0d2a269a4a2dfe69a8/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028E15BE5040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))