{"uuid": "0f057b7a-7235-4abf-8d60-48446243061c", "children": ["53bfed0f-484f-44d4-b7db-22cc4ece2152"], "befores": [{"name": "create_invoice_test_data", "status": "failed", "statusDetails": {"message": "Failed: Could not load test data.\n", "trace": "  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\tests\\conftest.py\", line 98, in create_invoice_test_data\n    pytest.fail(\"Could not load test data.\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1744892179297, "stop": 1744892179299}], "start": 1744892179297, "stop": 1744892179751}