{"uuid": "47463fc5-bee0-438e-8248-247333dbace4", "children": ["851b1d40-0a58-40ec-a3ad-182702b27112"], "befores": [{"name": "setup", "status": "failed", "statusDetails": {"message": "Failed: Driver setup failed: Message: session not created\nfrom disconnected: unable to connect to renderer\nStacktrace:\n\tGetHandleVerifier [0x00CB7FD3+60707]\n\tGetHandleVerifier [0x00CB8014+60772]\n\t(No symbol) [0x00AE0683]\n\t(No symbol) [0x00B19454]\n\t(No symbol) [0x00B1443C]\n\t(No symbol) [0x00B0F4A9]\n\t(No symbol) [0x00B58D63]\n\t(No symbol) [0x00B5877A]\n\t(No symbol) [0x00B4CE46]\n\t(No symbol) [0x00B1C5D3]\n\t(No symbol) [0x00B1D424]\n\tGetHandleVerifier [0x00EFBAB3+2435075]\n\tGetHandleVerifier [0x00EF7053+2416035]\n\tGetHandleVerifier [0x00F133FC+2531660]\n\tGetHandleVerifier [0x00CCF0A5+155125]\n\tGetHandleVerifier [0x00CD5A4D+182173]\n\tGetHandleVerifier [0x00CBF8A8+91640]\n\tGetHandleVerifier [0x00CBFA50+92064]\n\tGetHandleVerifier [0x00CAA510+4704]\n\tBaseThreadInitThunk [0x75EB7BA9+25]\n\tRtlInitializeExceptionChain [0x7727C2EB+107]\n\tRtlClearBits [0x7727C26F+191]\n\n", "trace": "  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\tests\\conftest.py\", line 143, in setup\n    pytest.fail(f\"Driver setup failed: {e}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1745420179406, "stop": 1745420183662}], "start": 1745420179406, "stop": 1745420183766}