{"uuid": "ad3e0f24-e38b-4c81-a9e5-cbca45dcd95e", "children": ["e06a5a03-db3f-4614-954c-2f2b664efba5"], "befores": [{"name": "setup", "status": "passed", "start": 1745242613703, "stop": 1745242619256}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00EE8073+60707]\n\tGetHandleVerifier [0x00EE80B4+60772]\n\t(No symbol) [0x00D104FE]\n\t(No symbol) [0x00D4B898]\n\t(No symbol) [0x00D7CF06]\n\t(No symbol) [0x00D789D5]\n\t(No symbol) [0x00D77F66]\n\t(No symbol) [0x00CE36E5]\n\t(No symbol) [0x00CE3C3E]\n\t(No symbol) [0x00CE40CD]\n\tGetHandleVerifier [0x0112BB53+2435075]\n\tGetHandleVerifier [0x011270F3+2416035]\n\tGetHandleVerifier [0x0114349C+2531660]\n\tGetHandleVerifier [0x00EFF145+155125]\n\tGetHandleVerifier [0x00F05AED+182173]\n\t(No symbol) [0x00CE33B0]\n\t(No symbol) [0x00CE2BC3]\n\tGetHandleVerifier [0x0124D23C+3620588]\n\tBaseThreadInitThunk [0x75EB7BA9+25]\n\tRtlInitializeExceptionChain [0x7727C2EB+107]\n\tRtlClearBits [0x7727C26F+191]\n\n", "trace": "  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\tests\\conftest.py\", line 141, in setup\n    logout(driver)\n    ~~~~~~^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\tests\\conftest.py\", line 163, in logout\n    logout_page.click_logged_out_profile()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\pages\\login_page.py\", line 50, in click_logged_out_profile\n    self.actions.wait_for_element(self.logged_out_profile)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\actions\\actions.py\", line 68, in wait_for_element\n    WebDriverWait(self.driver, timeout).until(EC.visibility_of_element_located(locator))\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 137, in until\n    value = method(self._driver)\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 224, in _predicate\n    return _element_if_visible(driver.find_element(*locator))\n                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 898, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\Taurus13\\PycharmProjects\\PythonProject\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1745242624652, "stop": 1745242624669}], "start": 1745242613703, "stop": 1745242624669}